# Generated by Django 4.2.5 on 2023-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0004_alter_testimonial_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='contact',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
