# Generated by Django 4.2.5 on 2023-09-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0005_projects_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='contact',
        ),
    ]
