# Generated by Django 4.2.5 on 2023-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0007_rename_owner_projects_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='progress',
            field=models.PositiveIntegerField(default=75),
        ),
    ]
