# Generated by Django 4.2.5 on 2023-09-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0008_skillset_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=50)),
                ('Certification', models.CharField(max_length=50)),
                ('Entry_year', models.IntegerField()),
                ('Final_year', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyData.figure')),
            ],
        ),
    ]
