# Generated by Django 4.2.5 on 2023-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0009_figure_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
