# Generated by Django 4.2.5 on 2023-10-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0011_rename_firstname_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
