# Generated by Django 4.2.5 on 2023-10-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyData', '0012_message_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='unread',
            new_name='read',
        ),
    ]
